export default {
    TOGGLE_ADDMODE       : 'TOGGLE_ADDMODE',
    SUBMIT_ADD           : 'SUBMIT_ADD',
    CANCEL_ADD           : 'CANCEL_ADD',
    SELECT_OBSERVATION   : 'SELECT_OBSERVATION',
    UNSELECT_OBSERVATION : 'UNSELECT_OBSERVATION',
    FETCH_OBSERVATIONS   : 'FETCH_OBSERVATIONS',
    FETCH_COMPLETE       : 'FETCH_COMPLETE',
    FETCH_ERROR          : 'FETCH_ERROR',
    FORM_CHANGED         : 'FORM_CHANGED',
    FORMDATA_POSTED      : 'FORMDATA_POSTED',
    FORM_ERROR           : 'FORM_ERROR',
    REMOVE_ALERT         : 'REMOVE_ALERT',
    TOGGLE_TESTMODE      : 'TOGGLE_TESTMODE'
}
